config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :tilemaps
  get '/upload', to: 'tilemaps#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tilemap.rb
class Tilemap < ApplicationRecord
  has_one_attached :tilemap_data
  has_one_attached :tileset
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @tilemap = Tilemap.last
    redirect_to('/upload', flash: { alert: "No tilemaps. Please upload one." }) if @tilemap.nil?
  end

end

app/controllers/tilemaps_controller.rb
class TilemapsController < ApplicationController

  layout 'admin'

  def index
    @tilemaps = Tilemap.all
  end

  def new
    @tilemap = Tilemap.new
  end

  def edit
    @tilemap = Tilemap.find(params[:id])
  end

  def create
    @tilemap = Tilemap.new(tilemap_params)
    if @tilemap.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    @tilemap = Tilemap.find(params[:id])
    if @tilemap.update_attributes(tilemap_params)
      redirect_to tilemaps_path
    else
      render :edit
    end
  end

  def destroy 
    @tilemap = Tilemap.find(params[:id])
    redirect_to tilemaps_path
  end

  private
  def tilemap_params
    params.require(:tilemap).permit(:name, :tilemap_data, :tileset)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tilemaps_helper.rb
module TilemapsHelper
end

app/views/home/index.html.erb
<% content_for :inline_scripts do %>
<script>
  var game = window.game;
  game.loadZone({
    tileset: "<%= url_for(@tilemap.tileset) %>",
    tilemapData: "<%= url_for(@tilemap.tilemap_data) %>"
  }); 
  game.launch();
</script>
<% end %>

<div id="game-container"></div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diluvia | Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <style>
      html, body {
        background: #f9fafb;
      }
      #body {
        margin-top: 6rem;
      }
    </style>
  </head>
  <body>
    <div id="body">
      <div class="ui grid container centered">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diluvia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= yield :inline_styles %>
    <%= yield :inline_scripts %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<div id="error_explanation">
  <ul>
  <% errors.full_messages.each do |msg| %>
    <li>* <%= msg %></li>
  <% end %>
  </ul>
</div>

app/views/shared/_flashes.html.erb
<div id="alert">
  <%=flash[:alert]%>
</div>

app/views/tilemaps/_form.html.erb
<div class="field">
  <%= form.label :name, "Name" %>
  <%= form.text_field :name %>
</div>
<div class="field">
  <% extraLabel = form.object.persisted? ? (": " + form.object.tilemap_data.filename.to_s) : "" %>
  <%= form.label :tilemap_data, "<i class='file icon'></i> Tilemap#{extraLabel}".html_safe %>
  <%= form.file_field :tilemap_data %>
  <small><em>Accepts .json format</em></small>
</div>
<div class="field">
  <% extraLabel = form.object.persisted? ? (": " + form.object.tileset.filename.to_s) : "" %>
  <%= form.label :tileset, "<i class='file image icon'></i> Tileset#{extraLabel}".html_safe  %>
  <%= form.file_field :tileset %>
  <small><em>Accepts images</em></small>
</div>

app/views/tilemaps/_tilemap.html.erb
<tr>
  <td><%= tilemap.id %></td>
  <td><%= link_to tilemap.name, edit_tilemap_url(tilemap) %></td>
  <td>
    <i class="file icon"></i> 
    <%= tilemap.tilemap_data.filename %>
  </td>
  <td>
    <i class="file image icon"></i> 
    <%= tilemap.tileset.filename %>
  </td>
</tr>

app/views/tilemaps/edit.html.erb
<div class="eight wide column">
  <h1 class="ui header">Edit Tilemap</h1>

  <%= render partial: "shared/alerts" if flash[:alert] %>
  <%= render partial: "shared/errors", locals: { errors: @tilemap.errors } if @tilemap.errors.any? %>
  <div class="ui segment">
    <div id="uploadform">
      <%= form_for @tilemap, html: { multipart: true, class: "ui form" } do |form| %>
        <%= render partial: "form", locals: { form: form } %>
        <div class="field">
          <%= form.submit "Save", class: "ui primary button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tilemaps/index.html.erb
<div class="twelve wide column">
  <table class="ui celled striped table">
    <thead>
      <tr><th colspan="4">
        <div class="ui clearing">
          <%= link_to "Upload Tilemap", new_tilemap_url, class: "ui right floated positive mini button" %>
          <h3 class="ui left floated header">
            Tilemaps
          </h3>
        </div>
      </tr></thead>
    <tbody>
      <%= render partial: "tilemap", collection: @tilemaps %>
    </tbody>
  </table>
</div>

app/views/tilemaps/new.html.erb
<% if flash[:alert] %>
  <div id="alert">
    <%=flash[:alert]%>
  </div>
<% end %>

<% if @tilemap.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @tilemap.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div id="uploadform">
<%= form_for :tilemap, url: {action: "create"}, html: { multipart: true } do |form| %>
  <div>
    <%= form.label :name, 'Name: ' %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :tilemap_data, 'Tilemap: ' %>
    <%= form.file_field :tilemap_data %>
  </div>
  <div>
    <%= form.label :tilesets, 'Tilesets: '  %>
    <%= form.file_field :tileset %>
  </div>
  <div>
    <%= form.submit "Upload" %>
  </div>
<% end %>
</div>


<% content_for :inline_styles do %>
<style>
    body {
      font-family: helvetica;
    }
    #alert, #uploadform form {
      width: 400px;
      margin: 0 auto;
    }
    #alert {
      background: #FCC;
      text-align: center;
      padding: 5px 0;
    }
    #uploadform form {
      background: #DDD;
      padding: 1px 0;
    }
    #uploadform form div {
      margin: 20px 10px;
      padding: 10px;
      background: #CDCDCD;
    }
</style>
<% end %>

app/views/tilesets/new.html.erb
<% if flash[:alert] %>
  <div id="alert">
    <%=flash[:alert]%>
  </div>
<% end %>

<% if @tileset.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @tileset.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div id="uploadform">
<%= form_for :tileset, url: {action: "create"}, html: { multipart: true } do |form| %>
  <div>
    <%= form.label :name, 'Name: ' %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :tileset_data, 'Tileset: ' %>
    <%= form.file_field :tileset_data %>
  </div>
  <div>
    <%= form.label :tilemap, 'Tilemap: '  %>
    <%= form.file_field :tilemap %>
  </div>
  <div>
    <%= form.submit("Upload") %>
  </div>
<% end %>
</div>


<% content_for :inline_styles do %>
<style>
    body {
      font-family: helvetica;
    }
    #alert, #uploadform form {
      width: 400px;
      margin: 0 auto;
    }
    #alert {
      background: #FCC;
      text-align: center;
      padding: 5px 0;
    }
    #uploadform form {
      background: #DDD;
      padding: 1px 0;
    }
    #uploadform form div {
      margin: 20px 10px;
      padding: 10px;
      background: #CDCDCD;
    }
</style>
<% end %>